--- 
- name: Update a VCN 
  hosts: localhost 
  gather_facts: false
  tasks: 
   - name: Update the existing simple VCN 
     oracle.oci.oci_network_vcn: 
       vcn_id: "ocid1.vcn.oc1.iad.amaaaaaa3ow6m3ya25iobfke37rjyzxfonugheygr735ftsxvfhllw5jsfcq"
       display_name: AnsibleVCN 
     register: result 
   - debug: msg="{{ result }}"